version: '3.8'

services:
  git-analyzer:
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c "npm install && node index.js"
    environment:
      - GIT_REPO_URL=${GIT_REPO_URL}
